### ISSUE TITLE
Crashes when internet connection is lost

### ISSUE THREAD

**Issue by iskoch01** [khoazero123/node-red-contrib-blynk-api#2]
Can't seem to keep this node from crashing node-red when the internet connection is lost, and I have a global error handler. Here is a sample message:

13 Feb 23:24:27 - [red] Uncaught Exception:
13 Feb 23:24:27 - Error: WebSocket is not open: readyState 0 (CONNECTING)
    at WebSocket.send (C:\Users\Administrator\.node-red\node_modules\ws\lib\webs
ocket.js:327:13)
    at BlynkClientNode.login (C:\Users\Administrator\.node-red\node_modules\node
-red-contrib-blynk-api\blynk-api.js:329:17)
    at WebSocket.<anonymous> (C:\Users\Administrator\.node-red\node_modules\node
-red-contrib-blynk-api\blynk-api.js:216:14)
    at WebSocket.emit (events.js:321:20)
    at WebSocket.setSocket (C:\Users\Administrator\.node-red\node_modules\ws\lib
\websocket.js:172:10)
    at ClientRequest.<anonymous> (C:\Users\Administrator\.node-red\node_modules\
ws\lib\websocket.js:646:15)
    at ClientRequest.emit (events.js:321:20)
    at Socket.socketOnData (_http_client.js:510:11)
    at Socket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:294:12)

**Comment by khoazero123** [comment]
@iskoch01 I'm so sorry for the delay, I've been so busy with so many projects to do. I just released version `0.0.8` to fix the above problem.
